version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_prisma_demo
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123       
      MYSQL_DATABASE: prisma_demo           
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
